server:
  port: 7002
spring:
  application:
    name: ad-dashbord
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"